# Generated by Django 5.1.7 on 2026-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('tree_index', models.JSONField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('text_chunks', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_summaries', models.JSONField(default=list)),
                ('all_sections', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
