# Generated by Django 5.1.7 on 2026-03-28 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('original_text', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('summary', 'Summary'), ('chunk', 'Chunk')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page', 'source_type'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentIndex',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='processing_error',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_chunks',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tree_index',
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='region',
            field=models.CharField(choices=[('eu', 'European Union'), ('india', 'India'), ('us', 'United States')], default='india', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rag_app.document'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='rag_app.documentpage'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
    ]
