# Generated by Django 5.1.7 on 2026-04-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_documentpage_searchindex_delete_documentindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_ocred',
            field=models.BooleanField(default=False, help_text='True if any page in this document required OCR'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_confidence_avg',
            field=models.FloatField(blank=True, help_text='Average OCR confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='chunk_type',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('list', 'List')], default='text', help_text='Type of content in this chunk', max_length=20),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='is_ocr_generated',
            field=models.BooleanField(default=False, help_text='True if this text came from OCR processing'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='section_title',
            field=models.CharField(blank=True, default='', help_text="Header/section this chunk belongs to (e.g., 'Import Procedures')", max_length=500),
        ),
    ]
