# Generated by Django 5.1.7 on 2026-04-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_document_is_ocred_document_ocr_confidence_avg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchindex',
            options={'ordering': ['page', 'source_type', 'chunk_level']},
        ),
        migrations.AddField(
            model_name='searchindex',
            name='char_start',
            field=models.IntegerField(blank=True, help_text='Character position where this chunk starts in original text', null=True),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='chunk_level',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='child', help_text='Whether this is a parent (large context) or child (precise retrieval) chunk', max_length=10),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='document_size',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size category of the source document', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='parent_chunk',
            field=models.ForeignKey(blank=True, help_text='Parent chunk for child entries, None for parent entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_chunks', to='rag_app.searchindex'),
        ),
    ]
