# Generated by Django 5.1.7 on 2026-04-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_alter_searchindex_options_searchindex_char_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField(blank=True, default='', help_text='Comma-separated topic tags extracted by LLM')),
                ('commodities', models.TextField(blank=True, default='', help_text='Comma-separated commodities mentioned')),
                ('regulations', models.TextField(blank=True, default='', help_text='Comma-separated regulations/policies referenced')),
                ('summary', models.TextField(blank=True, default='', help_text='200-word overview of the entire document')),
                ('key_facts', models.TextField(blank=True, default='', help_text='JSON dict of key facts extracted by LLM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='rag_app.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(choices=[('quantity_limit', 'Quantity Limit'), ('deadline', 'Deadline'), ('requirement', 'Requirement'), ('penalty', 'Penalty'), ('exemption', 'Exemption'), ('procedure_step', 'Procedure Step'), ('fee_rate', 'Fee or Rate'), ('eligibility', 'Eligibility Criteria'), ('document_type', 'Document Type'), ('other', 'Other')], default='other', help_text='Category of this fact', max_length=30)),
                ('subject', models.CharField(default='', help_text="Topic/subject of this fact (e.g., 'wheat_export')", max_length=200)),
                ('value', models.TextField(help_text='The extracted fact value')),
                ('condition', models.TextField(blank=True, default='', help_text='Conditions or qualifiers for this fact')),
                ('raw_text', models.TextField(help_text='Exact sentence/paragraph the fact came from')),
                ('confidence', models.FloatField(default=0.0, help_text='LLM confidence in this extraction (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, help_text='The SearchIndex chunk this fact was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facts', to='rag_app.searchindex')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='rag_app.documentpage')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'indexes': [models.Index(fields=['fact_type', 'subject'], name='rag_app_fac_fact_ty_d1f479_idx'), models.Index(fields=['page', 'fact_type'], name='rag_app_fac_page_id_305d5a_idx')],
            },
        ),
    ]
