# Generated by Django 5.1.7 on 2026-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0005_add_document_metadata_and_fact_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Model used to generate the embedding', max_length=100, null=True),
        ),
    ]
